{{- if .Values.albMaster.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.albMaster.name }}-master-alb
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.albMaster.name }}
    env: {{ .Values.environment }}
    type: master-alb
  annotations:
    # AWS Load Balancer Controller - Master ALB
    alb.ingress.kubernetes.io/group.name: {{ .Values.albMaster.groupName | quote }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.albMaster.annotations.awsListenPorts | quote }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.albMaster.annotations.awsTargetType | default "ip" }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.albMaster.annotations.awsBackendProtocol | default "HTTP" }}
    alb.ingress.kubernetes.io/success-codes: {{ .Values.albMaster.annotations.awsSuccessCodes | default "200" }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.albMaster.annotations.awsHealthcheckPath | default "/health" }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.albMaster.annotations.awsScheme | default "internal" }}
    
    # Load Balancer Configuration
    {{- if .Values.albMaster.annotations.awsLoadBalancerName }}
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.albMaster.annotations.awsLoadBalancerName | quote }}
    {{- end }}
    {{- if .Values.albMaster.annotations.awsSubnets }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.albMaster.annotations.awsSubnets | quote }}
    {{- end }}
    {{- if .Values.albMaster.annotations.awsSecurityGroups }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.albMaster.annotations.awsSecurityGroups | quote }}
    {{- end }}
    
    # SSL/TLS Configuration
    {{- if .Values.albMaster.ssl.enabled }}
    alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.albMaster.ssl.redirect | quote }}
    {{- if .Values.albMaster.ssl.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.albMaster.ssl.certificateArn | quote }}
    {{- end }}
    {{- if .Values.albMaster.ssl.policy }}
    alb.ingress.kubernetes.io/ssl-policy: {{ .Values.albMaster.ssl.policy | quote }}
    {{- end }}
    {{- end }}

    # mTLS Configuration
    {{- if and .Values.albMaster.mtls.enabled .Values.albMaster.mtls.mutualAuthentication }}
    alb.ingress.kubernetes.io/mutual-authentication: {{ .Values.albMaster.mtls.mutualAuthentication | toJson | quote }}
    {{- end }}

    # WAF Configuration
    {{- if .Values.albMaster.waf.enabled }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.albMaster.waf.aclArn | quote }}
    {{- end }}

    # Custom annotations
    {{- range $key, $value := .Values.albMaster.annotations.custom }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

spec:
  ingressClassName: {{ .Values.albMaster.className }}

  {{- if and .Values.albMaster.ssl.enabled .Values.albMaster.ssl.hosts }}
  tls:
    {{- range .Values.albMaster.ssl.hosts }}
    - hosts:
        - {{ .host | quote }}
      {{- if .secretName }}
      secretName: {{ .secretName }}
      {{- end }}
    {{- end }}
  {{- end }}

  rules:
    - http:
        paths:
        - path: {{ .Values.albMaster.defaultPath | default "/" }}
          pathType: {{ .Values.albMaster.defaultPathType | default "Prefix" }}
          backend:
            service:
              name: {{ .Values.albMaster.defaultService.name }}
              port:
                number: {{ .Values.albMaster.defaultService.port }}
{{- end }}