apiVersion: v2
name: eks-controllers
description: EKS Controllers bundle - AWS Load Balancer Controller & Cluster Autoscaler
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: aws-load-balancer-controller
    version: 1.16.0
    repository: https://aws.github.io/eks-charts
    condition: aws-load-balancer-controller.enabled
  
  - name: cluster-autoscaler
    version: 9.54.0
    repository: https://kubernetes.github.io/autoscaler
    condition: cluster-autoscaler.enabled
