{{- if .Values.nodepool.enabled }}
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ include "eks-controllers.nodepool.name" . }}
  {{- with .Values.nodepool.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.nodepool.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- if .Values.nodepool.template.labels }}
      labels:
        {{- toYaml .Values.nodepool.template.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.nodepool.template.annotations }}
      annotations:
        {{- toYaml .Values.nodepool.template.annotations | nindent 8 }}
      {{- end }}
    spec:
      nodeClassRef:
        group: {{ .Values.nodepool.nodeClassRef.group | default "eks.amazonaws.com" }}
        kind: {{ .Values.nodepool.nodeClassRef.kind | default "NodeClass" }}
        name: {{ .Values.nodepool.nodeClassRef.name | default (include "eks-controllers.nodeclass.name" .) }}
      
      {{- if .Values.nodepool.requirements }}
      requirements:
        {{- range .Values.nodepool.requirements }}
        - key: {{ .key | quote }}
          operator: {{ .operator }}
          values:
            {{- range .values }}
            - {{ . | quote }}
            {{- end }}
        {{- end }}
      {{- end }}
      
      {{- if .Values.nodepool.taints }}
      taints:
        {{- range .Values.nodepool.taints }}
        - key: {{ .key | quote }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- end }}
          effect: {{ .effect }}
        {{- end }}
      {{- end }}
      
      {{- if .Values.nodepool.startupTaints }}
      startupTaints:
        {{- range .Values.nodepool.startupTaints }}
        - key: {{ .key | quote }}
          {{- if .value }}
          value: {{ .value | quote }}
          {{- end }}
          effect: {{ .effect }}
        {{- end }}
      {{- end }}
      
      {{- if .Values.nodepool.expireAfter }}
      expireAfter: {{ .Values.nodepool.expireAfter }}
      {{- end }}
      
      {{- if .Values.nodepool.terminationGracePeriod }}
      terminationGracePeriod: {{ .Values.nodepool.terminationGracePeriod }}
      {{- end }}
  
  {{- if .Values.nodepool.disruption }}
  disruption:
    {{- if .Values.nodepool.disruption.consolidationPolicy }}
    consolidationPolicy: {{ .Values.nodepool.disruption.consolidationPolicy }}
    {{- end }}
    {{- if .Values.nodepool.disruption.consolidateAfter }}
    consolidateAfter: {{ .Values.nodepool.disruption.consolidateAfter }}
    {{- end }}
    {{- if .Values.nodepool.disruption.budgets }}
    budgets:
      {{- range .Values.nodepool.disruption.budgets }}
      - nodes: {{ .nodes | quote }}
        {{- if .schedule }}
        schedule: {{ .schedule | quote }}
        {{- end }}
        {{- if .duration }}
        duration: {{ .duration }}
        {{- end }}
        {{- if .reasons }}
        reasons:
          {{- range .reasons }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  
  {{- if .Values.nodepool.limits }}
  limits:
    {{- if .Values.nodepool.limits.cpu }}
    cpu: {{ .Values.nodepool.limits.cpu | quote }}
    {{- end }}
    {{- if .Values.nodepool.limits.memory }}
    memory: {{ .Values.nodepool.limits.memory | quote }}
    {{- end }}
  {{- end }}
  
  {{- if .Values.nodepool.weight }}
  weight: {{ .Values.nodepool.weight }}
  {{- end }}
{{- end }}
