kind: HorizontalPodAutoscaler
metadata:
  name: microservicio-app-hpa
  namespace: ns-app-dev
  labels:
    app: microservicio-app
    env: 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservicio-app-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Percent
        value: 50
      - periodSeconds: 60
        type: Pods
        value: 2
      selectPolicy: Min
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - periodSeconds: 30
        type: Percent
        value: 100
      - periodSeconds: 30
        type: Pods
        value: 4
      selectPolicy: Max
      stabilizationWindowSeconds: 60
# Source: microservicio-base/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
